### ISSUE TITLE
Large images in control interface on imported guides for book lists

### ISSUE THREAD

**Issue by little9** [subjectsplus/SubjectsPlus#189]
![screen shot 2015-09-22 at 11 57 20 am](https://cloud.githubusercontent.com/assets/4324761/10023607/fdb29bc8-6120-11e5-8522-bb8ad774c7b8.png)

Here's the CSS that I used to neaten this up on the UM theme:

```css

.book {
	display: inline-block;
    line-height:1.3em;
    	font-size:.8em;
}

.book-cover-art {
    float:left;
    width: 30%;
    margin-right: 3%;
	clear:both;
}

.book-title {

}
.book-author {
	font-style:italic;
	

}
.book-call-number {

	
}
.book-description {

}
```
