### ISSUE TITLE
SP4:  Polish up UI for Videos.

### ISSUE THREAD

**Issue by agdarby** [subjectsplus/SubjectsPlus#212]
Right now, they aren't using the newest CSS.

**Comment by little9** [comment]
The form in the video pluslet is using the pure-form class, but those styles are being overridden with CSS:

```css
/* Pure Form overrides for guide page - PV */
.portal-column .pure-form input,
.portal-column .pure-form select,
.portal-column .pure-form textarea {
  border-radius: 2px !important; 
  border: 1px solid #bcbbbb !important; 
  box-shadow: none !important; 
  padding: 4px !important;
  font-size: 1em; 
  margin-bottom: 6px; 
  width: 45%;
  white-space: nowrap; 
}
```

Do you want to have a box-shadow in the inputs?
